version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - .:/app
    command: python -m backend.main

  frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
    command: streamlit run frontend/main.py --server.address 0.0.0.0